server:
  port: 8090
  servlet:
    context-path: /
    encoding:
      charset : UTF-8
      enabled: true
      force: true

spring:
  application:
    name: spring-security-jwt
  datasource:
#    url: jdbc:mysql://localhost:3306/spring_security_jwt
#    username: root
#    password: ${db_password}
    url: ${aws_db_url}
    username: ${aws_db_username}
    password: ${aws_db_password}

    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQL8Dialect

springdoc:
  swagger-ui:
    path: /api-test
    operationsSorter: alpha
    tags-sorter: alpha

jwt:
  secret:
    key: ${SECRET_KEY}